background-opacity = 0.88

background = #0B0E20
foreground = #DCD4BC
cursor-color = #F6D26C
cursor-text = #0B0E20

selection-background = #272B5E
selection-foreground = #FBFBF4

palette = 0=#0B0E20
palette = 1=#C85234
palette = 2=#8CAE3E
palette = 3=#E6B14A
palette = 4=#6E72C6
palette = 5=#8B67C0
palette = 6=#7FA3DC
palette = 7=#DCD4BC
palette = 8=#6E70A8
palette = 9=#E4703F
palette = 10=#BFD45C
palette = 11=#F6D26C
palette = 12=#8A8EDE
palette = 13=#AC8AE0
palette = 14=#A5C4F0
palette = 15=#FBFBF4
