background_opacity 0.88

background            #0B0E20
foreground            #DCD4BC
cursor                #F6D26C
cursor_text_color     #0B0E20

selection_background  #272B5E
selection_foreground  #FBFBF4

url_color             #7FA3DC

active_border_color   #A8BE4A
inactive_border_color #2B3068
active_tab_background   #272B5E
active_tab_foreground   #FBFBF4
inactive_tab_background #0B0E20
inactive_tab_foreground #6E70A8

color0  #0B0E20
color8  #6E70A8
color1  #C85234
color9  #E4703F
color2  #8CAE3E
color10 #BFD45C
color3  #E6B14A
color11 #F6D26C
color4  #6E72C6
color12 #8A8EDE
color5  #8B67C0
color13 #AC8AE0
color6  #7FA3DC
color14 #A5C4F0
color7  #DCD4BC
color15 #FBFBF4
